"""Read-only, fail-closed validation of APG138 roadmap governance records."""
from __future__ import annotations

import argparse
from datetime import date
import hashlib
import json
from pathlib import Path
import re
from typing import Any

import apg_roadmap_contract as contract

GOVERNANCE = Path("docs/governance")
MAX_BYTES = 512 * 1024
KINDS = {"object": dict, "array": list, "string": str, "boolean": bool, "null": type(None)}
WATCH_IDS = {"JACA-CI", "JACA-XO", "JACA-OUTBOX", "REPO-MAP", "DINAS-DEPLOYMENT"}


def unique_object(pairs: list[tuple[str, Any]]) -> dict:
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def load_json(path: Path) -> Any:
    if path.is_symlink() or path.stat().st_size > MAX_BYTES:
        raise ValueError("non-regular or oversized JSON")
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=unique_object)


def matches(value: Any, shape: dict) -> bool:
    """Validate only the closed schema vocabulary generated by our contract owner."""
    if "anyOf" in shape:
        return any(matches(value, choice) for choice in shape["anyOf"])
    if type(value) is not KINDS[shape["type"]]:
        return False
    if "const" in shape and value != shape["const"]:
        return False
    if "enum" in shape and value not in shape["enum"]:
        return False
    if isinstance(value, str):
        return bool(value.strip()) if shape.get("minLength") else True
    if isinstance(value, list):
        return (len({contract.fingerprint(item) for item in value}) == len(value)
                and all(matches(item, shape["items"]) for item in value))
    if isinstance(value, dict):
        fields = shape["properties"]
        return set(value) == set(fields) and all(matches(value[k], fields[k]) for k in fields)
    return True


def public_ref(root: Path, reference: str) -> bool:
    path = Path(reference.split("#", 1)[0])
    if path.is_absolute() or ".." in path.parts or not path.parts or path.parts[0] == "private":
        return False
    resolved = (root / path).resolve()
    return resolved.is_relative_to(root) and not resolved.is_relative_to(root / "private") and resolved.is_file()


def refs_valid(root: Path, refs: list[str]) -> bool:
    return bool(refs) and all(public_ref(root, value) for value in refs)


def load_records(root: Path) -> tuple[dict, list[str]]:
    records, errors = {}, []
    for kind, (filename, key, identity) in contract.FILES.items():
        try:
            expected = contract.schema(kind)
            actual = load_json(root / GOVERNANCE / "schemas" / (filename + ".schema.json"))
            if actual != expected:
                errors.append(kind + ": schema differs from maintained contract")
            data = load_json(root / GOVERNANCE / (filename + ".json"))
            if not matches(data, expected):
                errors.append(kind + ": invalid record shape")
                continue
            ids = [row[identity] for row in data[key]]
            if ids != sorted(set(ids)):
                errors.append(kind + ": duplicate or unordered identities")
            records[kind] = data
        except (OSError, ValueError, UnicodeError, RecursionError):
            errors.append(kind + ": unreadable or malformed JSON")
    return records, errors


def check_maintenance(root: Path, records: dict, errors: list[str]) -> dict:
    rows = {r["trigger_id"]: r for r in records["maintenance"]["triggers"]}
    if set(rows) != set(contract.TRIGGER_BINDINGS) | set(contract.MATURITY_TRIGGER_BINDINGS):
        errors.append("maintenance: frozen trigger identity mismatch")
    debts = {r["debt_id"]: r for r in load_json(root / GOVERNANCE / "language-profile-known-debt.json")["debts"]}
    fields = ("owner", "source_authority", "refresh_condition", "repair_condition", "affected_behavior",
              "blocks_stable", "evidence_required", "refresh_procedure")
    for identity, row in rows.items():
        if identity in contract.MATURITY_TRIGGER_BINDINGS:
            if not maturity_trigger_valid(root, row, debts):
                errors.append("maintenance: maturity lifecycle binding mismatch")
            continue
        bound = contract.fingerprint({field: row[field] for field in fields})
        valid = bound == contract.TRIGGER_BINDINGS.get(identity)
        valid &= refs_valid(root, row["source_authority"])
        if row["current_state"] != "UNKNOWN":
            valid &= refs_valid(root, row["state_evidence"])
        if identity in debts:
            valid &= row["affected_skills"] == [debts[identity]["profile"]]
            valid &= all(row[field] == debts[identity][field] for field in
                         ("owner", "refresh_condition", "repair_condition", "blocks_stable"))
        if identity not in debts:
            valid &= row["affected_skills"] == []
        if identity == "JS-QD-005" and row["current_state"] == "FALSE":
            valid &= row["interpretation"] == "JS_QD_005_REFRESH_NOT_TRIGGERED"
        if not valid:
            errors.append("maintenance: trigger/source/state binding mismatch")
    return rows


def maturity_trigger_valid(root: Path, row: dict, debts: dict) -> bool:
    """Bind a leaf-specific reopening observation, without reinterpreting debt refresh."""
    identity = row["trigger_id"]
    leaf = identity.removeprefix("MATURITY:")
    if contract.fingerprint(row) != contract.MATURITY_TRIGGER_BINDINGS.get(identity):
        return False
    reference = f"docs/governance/maturity/apg139/{leaf}.json"
    if row["affected_skills"] != [leaf] or row["state_evidence"] != [reference]:
        return False
    if not refs_valid(root, row["source_authority"]) or not public_ref(root, reference):
        return False
    try:
        candidate = load_json(root / reference)
        if not matches(candidate, contract.maturity_candidate_schema()):
            return False
        blocking = sorted(k for k, debt in debts.items()
                          if debt["profile"] == leaf and debt["blocks_stable"])
        return (candidate["skill_id"] == leaf
                and candidate["controlling_debt_ids"] == blocking
                and candidate["next_lifecycle_trigger"] == row["refresh_condition"]
                and candidate["evidence"]["repeated_positive_use"]["assessment"] in ("LIMITED", "MISSING")
                and all(all(public_ref(root, ref) for ref in evidence["references"])
                        for evidence in candidate["evidence"].values()))
    except (OSError, ValueError, UnicodeError, RecursionError):
        return False


def check_compatibility(root: Path, records: dict, errors: list[str]) -> dict:
    rows = {r["watch_id"]: r for r in records["compatibility"]["watches"]}
    if set(rows) != WATCH_IDS:
        errors.append("compatibility: required watch identity mismatch")
    for row in rows.values():
        valid = refs_valid(root, row["source_authority"])
        valid &= set(row["inherited_item_ids"]).issubset(contract.ITEM_BINDINGS)
        if row["status"] == "WATCH":
            valid &= not row["supported_cases"] and not row["qualification_evidence"]
        else:
            valid &= refs_valid(root, row["qualification_evidence"])
        if row["status"] == "QUALIFIED" or row["supported_cases"]:
            valid &= all(row[key] for key in ("observed_revision", "observed_contract", "observation_date", "fixture_identity"))
            valid &= bool(row["supported_cases"])
        if row["observation_date"] is not None:
            try:
                valid &= date.fromisoformat(row["observation_date"]).isoformat() == row["observation_date"]
            except ValueError:
                valid = False
        fixture = row["fixture_identity"]
        if fixture is not None:
            valid &= public_ref(root, fixture["path"])
            if valid:
                valid &= hashlib.sha256((root / fixture["path"]).read_bytes()).hexdigest() == fixture["sha256"]
        if not valid:
            errors.append("compatibility: unavailable evidence or unsupported qualification claim")
    return rows


def catalog(root: Path) -> dict:
    text = (root / "skills/README.md").read_text(encoding="utf-8")
    table = text.split("## Current development catalog", 1)[1].split("\n## ", 1)[0]
    entries = re.findall(r"^\| \[`([^`]+)`\]\(([^)]+)\) \| .* \| `(stable|provisional|deprecated)` \|$", table, re.M)
    result = {name: (str(Path("skills") / path), maturity) for name, path, maturity in entries}
    if len(result) != len(entries):
        raise ValueError("duplicate catalog skill")
    return result


def maturity_decision_valid(root: Path, row: dict, maintenance: dict) -> bool:
    status = row["disposition_status"]
    if status in ("EXISTING_STABLE", "PENDING_V0110_B"):
        valid = row["current_maturity"] == ("stable" if status == "EXISTING_STABLE" else "provisional")
        if status == "PENDING_V0110_B" and row.get("maintenance_ref") is not None:
            trigger = maintenance.get(row["maintenance_ref"], {})
            valid &= row["maintenance_ref"] == "MATURITY:" + row["skill_id"]
            valid &= row["next_lifecycle_trigger"] == trigger.get("refresh_condition")
            valid &= row["independent_review"] is None
        return valid
    if not row["independent_review"] or not public_ref(root, row["independent_review"]):
        return False
    if not all(refs_valid(root, refs) for refs in row["evidence"].values()):
        return False
    if status == "STABLE":
        return row["current_maturity"] == "stable" and not row["blocking_debts"]
    if status == "PROVISIONAL_MAINTENANCE":
        trigger = maintenance.get(row["maintenance_ref"])
        return (row["current_maturity"] == "provisional" and trigger is not None
                and row["maintenance_ref"] == "MATURITY:" + row["skill_id"]
                and trigger["current_state"] == "FALSE"
                and trigger["affected_skills"] == [row["skill_id"]]
                and row["next_lifecycle_trigger"] == trigger["refresh_condition"])
    return row["current_maturity"] == "deprecated"


def check_maturity(root: Path, records: dict, maintenance: dict, errors: list[str]) -> dict:
    rows = {r["skill_id"]: r for r in records["maturity"]["skills"]}
    entries = catalog(root)
    canonical = {str(p.relative_to(root)) for p in (root / "skills").rglob("SKILL.md")}
    if set(rows) != set(entries) or len(rows) != 45 or canonical != {p for p, _ in entries.values()}:
        errors.append("maturity: canonical/catalog/ledger identity mismatch")
    debt_authority = load_json(root / GOVERNANCE / "language-profile-known-debt.json")
    debts = debt_authority["debts"]
    projections = root / ".agents/skills"
    if {p.name for p in projections.iterdir()} != set(rows):
        errors.append("maturity: projection inventory mismatch")
    for identity, row in rows.items():
        expected_debt = sorted(r["debt_id"] for r in debts if r["profile"] == identity and r["blocks_stable"])
        projection = projections / identity
        valid = entries.get(identity) == (row["path"], row["current_maturity"])
        valid &= public_ref(root, row["path"]) and projection.is_symlink()
        valid &= projection.resolve() == (root / row["path"]).parent.resolve()
        valid &= sorted(row["blocking_debts"]) == expected_debt
        valid &= row["debt_authority"] == contract.DEBT_AUTHORITY
        valid &= row["active_debts"] == sorted(r["debt_id"] for r in debts if r["profile"] == identity)
        valid &= row["resolved_debts"] == sorted(r["debt_id"] for r in debt_authority["resolutions"]
                                               if r["original_entry"]["profile"] == identity)
        valid &= row["required_evidence_categories"] == list(contract.EVIDENCE_CATEGORIES)
        valid &= refs_valid(root, row["source_references"])
        valid &= maturity_decision_valid(root, row, maintenance)
        if identity in contract.PROVISIONAL and row["disposition_status"] == "EXISTING_STABLE":
            valid = False
        if not valid:
            errors.append("maturity: path/projection/debt/evidence mismatch")
    return rows


def disposition_valid(root: Path, row: dict, linked: tuple[dict, dict, dict]) -> bool:
    status, decision = row["status"], row["disposition"]
    if status == "OPEN":
        return decision is None
    if status not in row["allowed_outcomes"] or decision is None:
        return False
    refs = [decision["decision_ref"], decision["review_ref"], *decision["qualification_refs"]]
    if not decision["qualification_refs"] or not refs_valid(root, refs):
        return False
    maintenance, compatibility, maturity = linked
    if status == "MAINTENANCE_TRIGGER":
        trigger = maintenance.get(decision["maintenance_ref"])
        return (trigger is not None and trigger["current_state"] == "FALSE"
                and decision["maintenance_ref"] == row["trigger_ref"])
    if status == "CONSUMER_HANDOFF_CLOSED":
        watch = compatibility.get(decision["compatibility_ref"])
        return (watch is not None and watch["status"] == "HANDOFF_CLOSED"
                and row["item_id"] in watch["inherited_item_ids"])
    if row["inherited_class"] == "PROVISIONAL_MATURITY":
        identity = row["item_id"].removeprefix("MATURITY:")
        leaf = maturity.get(decision["maturity_ref"])
        return (leaf is not None and decision["maturity_ref"] == identity
                and leaf["disposition_status"] == status
                and leaf.get("independent_review") == decision["review_ref"]
                and leaf.get("maintenance_ref") == decision["maintenance_ref"])
    return True


def receipt_valid(root: Path, row: dict, maturity: dict | None = None,
                  maintenance: dict | None = None) -> bool:
    """Require typed, item-bound evidence; reference existence is not acceptance."""
    decision = row["disposition"]
    if row["status"] == "OPEN":
        return decision is None
    if decision is None or not public_ref(root, decision["decision_ref"]):
        return False
    try:
        receipt = load_json(root / decision["decision_ref"])
        valid = matches(receipt, contract.decision_schema())
        if not valid:
            return False
        valid &= receipt["item_id"] == row["item_id"] and receipt["outcome"] == row["status"]
        valid &= receipt["closure_phase"] == row["closure_phase"]
        valid &= receipt["author"].strip().casefold() != receipt["reviewer"].strip().casefold()
        valid &= all(refs_valid(root, refs) for refs in receipt["evidence"].values())

        if maturity is not None and row["inherited_class"] == "PROVISIONAL_MATURITY":
            leaf = maturity.get(row["item_id"].removeprefix("MATURITY:"), {})
            if row["status"] in ("STABLE", "PROVISIONAL_MAINTENANCE"):
                valid &= receipt["evidence"] == leaf.get("evidence")
                valid &= receipt["evidence"]["independent_review"] == [decision["review_ref"]]

        if row["status"] == "MAINTENANCE_TRIGGER":
            if maintenance is None:
                return False
            trigger_ref = row.get("trigger_ref")
            if not trigger_ref or decision.get("maintenance_ref") != trigger_ref:
                return False
            trigger = maintenance.get(trigger_ref)
            if trigger is None or trigger.get("current_state") != "FALSE":
                return False
            evidence = receipt["evidence"]
            if evidence.get("independent_review") != [decision.get("review_ref")]:
                return False
            qual_refs = set(decision.get("qualification_refs") or [])
            obs_refs = set(evidence.get("trigger_observation") or [])
            proc_refs = set(evidence.get("refresh_procedure") or [])
            # Receipts retain their phase observations as the register accumulates evidence.
            if not obs_refs.issubset(set(trigger.get("state_evidence") or [])):
                return False
            if not obs_refs or not proc_refs:
                return False
            if not obs_refs.issubset(qual_refs) or not proc_refs.issubset(qual_refs):
                return False

        return valid
    except (OSError, ValueError, UnicodeError, RecursionError):
        return False


def check_closure(root: Path, records: dict, linked: tuple, errors: list[str]) -> dict:
    ledger = records["closure"]
    rows = ledger["items"]
    identities = {r["item_id"] for r in rows}
    expected = set(contract.ITEM_BINDINGS)
    unknown, missing = identities - expected, expected - identities
    if unknown or missing or len(rows) != len(expected):
        errors.append("closure: frozen inherited identity mismatch")
    if ledger["historical_exclusions"] != list(contract.HISTORICAL_EXCLUSIONS):
        errors.append("closure: historical exclusion mismatch")
    invalid = 0
    for row in rows:
        metadata = {k: v for k, v in row.items() if k not in ("status", "disposition")}
        valid = contract.fingerprint(metadata) == contract.ITEM_BINDINGS.get(row["item_id"])
        valid &= refs_valid(root, row["sources"])
        valid &= row["trigger_ref"] is None or row["trigger_ref"] in linked[0]
        valid &= disposition_valid(root, row, linked)
        valid &= receipt_valid(root, row, linked[2], linked[0])
        if not valid:
            invalid += 1
    if invalid:
        errors.append("closure: invalid frozen metadata or disposition evidence")
    open_ids = sorted(r["item_id"] for r in rows if r["status"] == "OPEN")
    return dict(expected_total=len(expected), total_inherited_rows=len(rows),
                terminal_rows=len(rows) - len(open_ids), open_rows=len(open_ids),
                invalid_rows=invalid, unknown_rows=len(unknown), missing_rows=len(missing))


def check_roadmap_closure(root: Path, require_zero: bool = False) -> dict:
    root = root.resolve()
    records, errors = load_records(root)
    try:
        if load_json(root / GOVERNANCE / "schemas/roadmap-decision.schema.json") != contract.decision_schema():
            errors.append("decision: schema differs from maintained contract")
        if load_json(root / GOVERNANCE / "schemas/maturity-candidate.schema.json") != contract.maturity_candidate_schema():
            errors.append("maturity candidate: schema differs from maintained contract")
    except (OSError, ValueError, UnicodeError, RecursionError):
        errors.append("decision: unreadable schema")
    if not all(public_ref(root, path) for path in contract.FOUNDATION_FILES):
        errors.append("foundation: missing or nonpublic required authority")
    totals = dict(expected_total=55, total_inherited_rows=0, terminal_rows=0,
                  open_rows=0, invalid_rows=0, unknown_rows=0, missing_rows=55)
    if len(records) == len(contract.FILES):
        try:
            maintenance = check_maintenance(root, records, errors)
            compatibility = check_compatibility(root, records, errors)
            maturity = check_maturity(root, records, maintenance, errors)
            totals = check_closure(root, records, (maintenance, compatibility, maturity), errors)
        except (OSError, ValueError, KeyError, IndexError, TypeError, UnicodeError):
            errors.append("source: unavailable or malformed governance authority")
    valid = not errors
    count = totals["open_rows"] if valid else None
    return {"schema_version": "apg.roadmap-closure-check/v1", "valid": valid,
            "passed": valid and (not require_zero or count == 0), **totals,
            "inherited_roadmap_open_items": count,
            "zero_backlog_qualified": valid and count == 0, "diagnostics": errors}


def main(arguments: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--require-zero", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(arguments)
    result = check_roadmap_closure(args.root, args.require_zero)
    if args.json:
        print(json.dumps(result, sort_keys=True))
    else:
        print(("PASS" if result["passed"] else "FAIL") + " roadmap closure: "
              + json.dumps(result, sort_keys=True))
    return 0 if result["passed"] else 1
