package hotspot

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestStableReadDetectsDriftAndCancellationDuringRead(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "large.go", "package p\n"+strings.Repeat("var X = 1\n", 100_000))
	request := testRequest(t, root)
	resolved, err := validateRoot(request.Root)
	if err != nil {
		t.Fatal(err)
	}
	scan := newScanner(context.Background(), context.Background(), request, resolved)
	_, _, err = scan.readStable("large.go", func() {
		if writeErr := os.WriteFile(filepath.Join(resolved, "large.go"), []byte("package changed\n"), 0o600); writeErr != nil {
			t.Fatal(writeErr)
		}
	})
	if !errors.Is(err, ErrFileDrift) {
		t.Fatalf("drift error = %v", err)
	}

	writeFixture(t, resolved, "large.go", "package p\n"+strings.Repeat("var X = 1\n", 100_000))
	cancelled, cancel := context.WithCancel(context.Background())
	scan = newScanner(cancelled, context.Background(), request, resolved)
	scan.readObserver = func(_ int) { cancel() }
	if _, _, err := scan.readStable("large.go", nil); !errors.Is(err, context.Canceled) {
		t.Fatalf("mid-read cancellation error = %v", err)
	}
}

func TestStructuredDepthAndMalformedSourcesRemainHonestRows(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "deep.json", strings.Repeat("[", maxStructuredDepth+1)+"0"+strings.Repeat("]", maxStructuredDepth+1))
	writeFixture(t, root, "deep.xml", strings.Repeat("<a>", maxStructuredDepth+1)+strings.Repeat("</a>", maxStructuredDepth+1))
	writeFixture(t, root, "broken.go", "package p\nfunc broken(\n")
	writeFixture(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage p\nfunc Generated() {}\n")
	report, err := Analyze(context.Background(), testRequest(t, root))
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"deep.json", "deep.xml", "broken.go"} {
		row := fileByPath(t, report, path)
		if row.ParseFailure == "" {
			t.Errorf("%s lacks parse failure", path)
		}
		if metricAvailability(t, row.Metrics, MetricNesting) != AvailabilityUnavailable {
			t.Errorf("%s nesting should be unavailable", path)
		}
	}
	generated := fileByPath(t, report, "generated.go")
	if !generated.Generated || generated.RankingEligible || generated.Ranking.AvailableWeight != 0 {
		t.Fatalf("generated policy = %#v", generated)
	}
}

func TestDefaultExclusionsAndUnbalancedHTML(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, ".git/private.go", "package private\n")
	writeFixture(t, root, "node_modules/dependency.js", "const x = 1\n")
	writeFixture(t, root, "source.html", "<main><p>open\n")
	report, err := Analyze(context.Background(), testRequest(t, root))
	if err != nil {
		t.Fatal(err)
	}
	if len(report.Files) != 1 || report.Files[0].Path != "source.html" {
		t.Fatalf("default exclusions = %#v", report.Files)
	}
	html := fileByPath(t, report, "source.html")
	if metricAvailability(t, html.Metrics, MetricNesting) != AvailabilityUnavailable {
		t.Fatalf("unbalanced HTML nesting = %#v", html.Metrics)
	}
}

func TestTotalBytesDepthUnreadableAndBinaryBounds(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "one.txt", strings.Repeat("a", 64))
	writeFixture(t, root, "two.txt", strings.Repeat("b", 64))
	request := testRequest(t, root)
	request.Limits.MaxBytesPerFile = 64
	request.Limits.MaxTotalBytes = 100
	if _, err := Analyze(context.Background(), request); !errors.Is(err, ErrLimitExceeded) {
		t.Fatalf("total-byte error = %v", err)
	}

	deepRoot := t.TempDir()
	current := deepRoot
	for index := 0; index < maxDirectoryDepth+1; index++ {
		current = filepath.Join(current, "d")
	}
	if err := os.MkdirAll(current, 0o700); err != nil {
		t.Fatal(err)
	}
	if _, err := Analyze(context.Background(), testRequest(t, deepRoot)); !errors.Is(err, ErrLimitExceeded) {
		t.Fatalf("directory-depth error = %v", err)
	}

	binaryRoot := t.TempDir()
	if err := os.WriteFile(filepath.Join(binaryRoot, "asset.png"), []byte{0, 1, 2, 3}, 0o600); err != nil {
		t.Fatal(err)
	}
	report, err := Analyze(context.Background(), testRequest(t, binaryRoot))
	if err != nil {
		t.Fatal(err)
	}
	if got := fileByPath(t, report, "asset.png").Language; got != LanguageBinary {
		t.Fatalf("binary classification = %s", got)
	}

	unreadableRoot := t.TempDir()
	writeFixture(t, unreadableRoot, "closed.go", "package p\n")
	closed := filepath.Join(unreadableRoot, "closed.go")
	if err := os.Chmod(closed, 0); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(closed, 0o600) })
	if _, err := Analyze(context.Background(), testRequest(t, unreadableRoot)); !errors.Is(err, ErrUnreadable) {
		if os.Geteuid() == 0 {
			t.Skip("root can read mode-zero fixture")
		}
		t.Fatalf("unreadable error = %v", err)
	}
}
